# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 09:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('third_name', models.CharField(max_length=100)),
                ('id_number', models.IntegerField(default=0)),
                ('district_of_birth', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('id_status', models.BooleanField(default=False)),
                ('gender', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='person', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Replacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10)),
                ('id_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electronic.Person')),
            ],
        ),
    ]
