# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electronic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Replacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10)),
                ('id_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electronic.Person')),
            ],
        ),
    ]
